name: PublishDocumentation

on: 
  push:
    tags: '*.*.*'

jobs:
  deploy_docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.publish_jazzy_docs }}
        config: .jazzy.yaml
